services:
  app:
    build:
      context: .
    container_name: roombooking-backend
    depends_on:
      postgres:
        condition: service_healthy
      mqtt:
        condition: service_started
    environment:
      DB_MODE: postgres
      DB_URL: jdbc:postgresql://postgres:5432/roombooking
      DB_USER: admin
      DB_PASSWORD: password
      DB_DRIVER: org.postgresql.Driver
      MQTT_BROKER_URL: tcp://mqtt:1883
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: roombooking-db
    environment:
      POSTGRES_DB: roombooking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d roombooking" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    container_name: roombooking-mqtt
    ports:
      - "1884:1883"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: roombooking-pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mci.edu
      PGADMIN_DEFAULT_PASSWORD: password
      PGPASSFILE: /pgpass
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./docker/pgadmin/pgpass:/pgpass:ro

volumes:
  postgres_data:
  pgadmin_data:
  mosquitto_data:
  mosquitto_log:
