ktor:
    application:
        modules:
            - edu.mci.ApplicationKt.module
    deployment:
        host: 0.0.0.0
        port: ${PORT:8080}

jwt:
    secret: "super-secret-key"
    issuer: "http://0.0.0.0:8080"
    audience: "http://0.0.0.0:8080"
    realm: "Access to room booking"

mqtt:
    brokerUrl: ${MQTT_BROKER_URL:tcp://localhost:1883}
    clientId: ${MQTT_CLIENT_ID:RoomBookingBackend}